routes/web.php
<?php


Auth::routes();
Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');

Route::redirect('/', '/login');
// Route::get('/home', function () {
//     if (session('status')) {
//         return redirect()->route('admin.home')->with('status', session('status'));
//     }

//     return redirect()->route('admin.home');
// });


// Route::get('/', 'Auth\LoginController@login')->name('login');
// Route::get('/admin/login', 'Admin\LoginController@login')->name('login');


Route::get('admin/login', 'Auth\LoginController@showAdminLoginForm')->name('auth.admin.login');
Route::get('register', 'Auth\RegisterController@showStudentRegisterForm')->name('auth.register.student');

Route::post('register', 'Auth\RegisterController@createStudent')->name('athu.register.student');
Route::get('get_by_classes', 'Admin\SubjectController@get_by_myclasses')->name('subjects.get_by_classes');

Route::get('/dashboard', function () {
    if (session('status')) {
        return redirect()->route('admin.dashboard')->with('status', session('status'));
    }

    return redirect()->route('admin.dashboard');
});

Route::group(['as' => 'user.','namespace' => 'User', 'middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('subjectsajaxData','HomeController@subjectAjaxData')->name('subjects.ajaxData');
    Route::get('/mycourse', 'HomeController@mycourse')->name('mycourse');
	Route::get('mycoursesubajaxData','HomeController@mycourseSubAjaxData')->name('mycourse.subAajaxData');
    Route::post('courseassignajaxData','HomeController@courseAssignAjaxData')->name('course.assignAjaxData');
    Route::get('chaptersajaxData','HomeController@chapterAjaxData')->name('chapters.ajaxData');
    Route::get('unitsajaxData','HomeController@unitAjaxData')->name('units.ajaxData');
    Route::get('qaajaxData','HomeController@QAAjaxData')->name('qa.ajaxData');
    Route::post('qaajaxData','HomeController@QAAjaxSubmitData')->name('qa.ajaxData');

    Route::get('/chapters/{id}', 'HomeController@chaptersIndex')->name('chapters'); 
    Route::get('/units/{id}', 'HomeController@unitsIndex')->name('units'); 
    Route::get('/qa/{id}', 'HomeController@QAIndex')->name('qa'); 

    Route::get('/profile', 'ProfileController@index')->name('profile'); 
    Route::post('/changepassword', 'ProfileController@changePassword')->name('changepassword');
});

//Clear all cache:
Route::get('clearall', function() {
    // $exitCode = Artisan::call('route:cache');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    return 'all cleared';
});




    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth','adminChecker']], function () {
    // Route::get('/', 'HomeController@index')->name('home'); 

    Route::get('/', 'DashboardController@index')->name('dashboard'); 



    Route::get('user-alerts/read', 'UserAlertsController@read');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('settings/permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('settings/roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('settings/users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // User Alerts
    Route::delete('user-alerts/destroy', 'UserAlertsController@massDestroy')->name('user-alerts.massDestroy');
    Route::resource('user-alerts', 'UserAlertsController', ['except' => ['edit', 'update']]);

    // Faq Categories
    Route::delete('faq-categories/destroy', 'FaqCategoryController@massDestroy')->name('faq-categories.massDestroy');
    Route::resource('faq-categories', 'FaqCategoryController');

    // Faq Questions
    Route::delete('faq-questions/destroy', 'FaqQuestionController@massDestroy')->name('faq-questions.massDestroy');
    Route::resource('faq-questions', 'FaqQuestionController');

    // Content Categories
    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
    Route::resource('content-categories', 'ContentCategoryController');

    // Content Tags
    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
    Route::resource('content-tags', 'ContentTagController');

    // Content Pages
    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
    Route::resource('content-pages', 'ContentPageController');

    // Boards
    Route::delete('boards/destroy', 'BoardController@massDestroy')->name('boards.massDestroy');
    Route::post('boards/media', 'BoardController@storeMedia')->name('boards.storeMedia');
    Route::resource('setup/boards', 'BoardController');
    Route::post('setup/boards/updates/{id}', 'BoardController@updates')->name('boards.updates');

    Route::get('ajaxData1','BoardController@ajaxData')->name('boards.ajaxData');
    Route::get('get_boards', 'BoardController@get_boards')->name('boards.get_boards');

    // My Classes
    Route::delete('my-classes/destroy', 'MyClassController@massDestroy')->name('my-classes.massDestroy');
    Route::post('my-classes/media', 'MyClassController@storeMedia')->name('my-classes.storeMedia');
    Route::resource('setup/my-classes', 'MyClassController');

    Route::get('ajaxData2','MyClassController@ajaxData')->name('my-classes.ajaxData');

    // Subjects
    Route::delete('subjects/destroy', 'SubjectController@massDestroy')->name('subjects.massDestroy');
    Route::post('subjects/media', 'SubjectController@storeMedia')->name('subjects.storeMedia');
    Route::resource('setup/subjects', 'SubjectController');
    
    Route::get('ajaxData3','SubjectController@ajaxData')->name('subjects.ajaxData');
    Route::get('get_by_classes', 'SubjectController@get_by_myclasses')->name('subjects.get_by_classes');

    // Chapters
    Route::delete('chapters/destroy', 'ChapterController@massDestroy')->name('chapters.massDestroy');
    Route::post('chapters/media', 'ChapterController@storeMedia')->name('chapters.storeMedia');
    Route::resource('setup/chapters', 'ChapterController');

    Route::get('ajaxData4','ChapterController@ajaxData')->name('chapters.ajaxData');
    Route::get('get_by_subjects', 'ChapterController@get_by_subjects')->name('chapters.get_by_subjects');
    Route::get('chapters/list', 'ChapterController@chapter_list')->name('chapters.list');

    // Units
    Route::delete('units/destroy', 'UnitController@massDestroy')->name('units.massDestroy');
    Route::post('units/media', 'UnitController@storeMedia')->name('units.storeMedia');
    Route::resource('units', 'UnitController');

    Route::get('ajaxData5','UnitController@ajaxData')->name('units.ajaxData');
    Route::get('get_by_chapters', 'UnitController@get_by_chapters')->name('units.get_by_chapters');
    Route::get('units/create', 'UnitController@create')->name('units.create');
    Route::post('units/sort_order', 'UnitController@sort_order')->name('units.sort_order');

    // Question Types
    Route::delete('question-types/destroy', 'QuestionTypeController@massDestroy')->name('question-types.massDestroy');
    Route::resource('question-types', 'QuestionTypeController');

    // Countries
    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountriesController');

    // States
    Route::delete('states/destroy', 'StateController@massDestroy')->name('states.massDestroy');
    Route::resource('states', 'StateController');

    // Cities
    Route::delete('cities/destroy', 'CityController@massDestroy')->name('cities.massDestroy');
    Route::resource('cities', 'CityController');

    // Students
    Route::delete('students/destroy', 'StudentController@massDestroy')->name('students.massDestroy');
    Route::resource('settings/students', 'StudentController');

    // Student Study Units
    Route::delete('student-study-units/destroy', 'StudentStudyUnitsController@massDestroy')->name('student-study-units.massDestroy');
    Route::resource('student-study-units', 'StudentStudyUnitsController');

    // Languages
    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
    Route::resource('languages', 'LanguageController');

    // Question Answers
    Route::delete('question-answers/destroy', 'QuestionAnswerController@massDestroy')->name('question-answers.massDestroy');
    Route::post('question-answers/media', 'QuestionAnswerController@storeMedia')->name('question-answers.storeMedia');
    Route::post('question-answers/parse-csv-import', 'QuestionAnswerController@parseCsvImport')->name('question-answers.parseCsvImport');
    Route::post('question-answers/process-csv-import', 'QuestionAnswerController@processCsvImport')->name('question-answers.processCsvImport');
    Route::resource('question-answers', 'QuestionAnswerController');

    Route::post('question-answers/sort_order', 'QuestionAnswerController@sort_order')->name('question-answers.sort_order');

    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');

app/Chapter.php
<?php

namespace App;

use App\Traits\Auditable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Chapter extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait, Auditable;

    public $table = 'chapters';

    protected $appends = [
        'image',
    ];

    public static $searchable = [
        'code',
        'name',
    ];

    const IS_ACTIVE_RADIO = [
        'yes' => 'Yes',
        'no'  => 'No',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    const STATUS_SELECT = [
        'draft'     => 'Draft',
        'review'    => 'Review',
        'published' => 'Published',
    ];

    protected $fillable = [
        'code',
        'name',
        'status',
        'board_id',
        'class_id',
        'is_active',
        'subject_id',
        'created_at',
        'updated_at',
        'deleted_at',
        'description',
        'modified_by_id',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function units()
    {
        return $this->hasMany(Unit::class, 'chapter_id', 'id');
    }

    public function studentStudyUnits()
    {
        return $this->hasMany(StudentStudyUnit::class, 'chapterid_id', 'id');
    }

    public function board()
    {
        return $this->belongsTo(Board::class, 'board_id');
    }

    function class()
    {
        return $this->belongsTo(MyClass::class, 'class_id');
    }

    public function subject()
    {
        return $this->belongsTo(Subject::class, 'subject_id');
    }

    public function getImageAttribute()
    {
        $file = $this->getMedia('image')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }

    public function modified_by()
    {
        return $this->belongsTo(User::class, 'modified_by_id');
    }
}

resources/views/admin/chapters/index.blade.php
@extends('layouts.adminpanel')
@section('content')
@can('chapter_create')
    <!-- <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.chapters.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.chapter.title_singular') }}
            </a>
        </div>
    </div> -->
@endcan
@include('partials.setupheader')

<!--modal window start-->
<div class="modal fade" id="addFormModal" tabindex="-1" role="dialog" aria-labelledby="addFormModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"><i class="fa fa-graduation-cap" aria-hidden="true"></i> <span id="addFormModalLabel">Add Class</span></h5>
                    <button type="button" class="close text-danger" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" id="add_form" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="_method" id="_method" value="POST"/>
                    <div class="form-group">
                        <select class="form-control {{ $errors->has('board') ? 'is-invalid' : '' }}" name="board_id" id="board_id" required>
                            @foreach($boards as $id => $board)
                                <option value="{{ $id }}" {{ old('board_id') == $id ? 'selected' : '' }}>{{ $board }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                       <select class="form-control {{ $errors->has('class') ? 'is-invalid' : '' }}" name="class_id" id="class_id" required>
                              <option value="">{{ trans('global.pleaseSelect') }}</option>
                        </select>
                    </div>
                    <div class="form-group">
                    <select class="form-control {{ $errors->has('subject') ? 'is-invalid' : '' }}" name="subject_id" id="subject_id" required>
                             <option value="">{{ trans('global.pleaseSelect') }}</option>
                    </select>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"  name="name" id="name" value="{{ old('name', '') }}"
                            placeholder="{{ trans('cruds.chapter.fields.name') }}" required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" name="code" id="code" value="{{ old('code', '') }}"
                            placeholder="{{ trans('cruds.chapter.fields.code') }}" required>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" placeholder="{{ trans('cruds.chapter.fields.description') }}"  name="description" id="description" value="{{ old('description', '') }}" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                    <img id="pre_img" style="display: none;"/>
                    <div class="upload-section">
                        <a href="#" class="upload-btn needsclick dropzone {{ $errors->has('image') ? 'is-invalid' : '' }}  dz-message" id="image-dropzone">
                            <span class="upload-icon dz-message" ><i class="fa fa-picture-o" aria-hidden="true"></i></span>
                            <span class="upload-text dz-message" data-dz-message>Upload Cover Image</span>
                        </a>
                    </div>
                    </div>

                    <div class="form-group">
                        <select class="form-control {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status" id="status" required>
                            <option value disabled {{ old('status', null) === null ? 'selected' : '' }}>{{ trans('global.chooseStatus') }}</option>
                            @foreach(App\Board::STATUS_SELECT as $key => $label)
                                <option value="{{ $key }}" {{ old('status', '') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <select class="form-control {{ $errors->has('is_active') ? 'is-invalid' : '' }}" name="is_active" id="is_active" required>
                            <option value disabled {{ old('is_active', null) === null ? 'selected' : '' }}>{{ trans('global.chooseEnableDisable') }}</option>
                        @foreach(App\Board::IS_ACTIVE_RADIO as $key => $label)
                              <option value="{{ $key }}" {{ old('is_active', '') === (string) $key ? 'selected' : '' }}>{{ $label == 'Yes'? 'Enable' : 'Disable' }}</option>
                        @endforeach
                        </select>
                    </div>
                    <input type="hidden" name="modified_by_id" id="modified_by_id" value="{{ Auth::user()->id }}"/>
                   

                </div>
                <div class="modal-footer text-center">
                    <button type="submit" id="submit" class="btn btn-primary btn-small">Add</button>
                    <button type="button" class="btn btn-light btn-small" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

  </div>
         </div>
     </main>

@endsection
@section('scripts')
@parent
<script>
//     $(function () {
//   let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
// @can('chapter_delete')
//   let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
//   let deleteButton = {
//     text: deleteButtonTrans,
//     url: "{{ route('admin.chapters.massDestroy') }}",
//     className: 'btn-danger',
//     action: function (e, dt, node, config) {
//       var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
//           return entry.id
//       });

//       if (ids.length === 0) {
//         alert('{{ trans('global.datatables.zero_selected') }}')

//         return
//       }

//       if (confirm('{{ trans('global.areYouSure') }}')) {
//         $.ajax({
//           headers: {'x-csrf-token': _token},
//           method: 'POST',
//           url: config.url,
//           data: { ids: ids, _method: 'DELETE' }})
//           .done(function () { location.reload() })
//       }
//     }
//   }
//   dtButtons.push(deleteButton)
// @endcan

//   let dtOverrideGlobals = {
//     buttons: dtButtons,
//     processing: true,
//     serverSide: true,
//     retrieve: true,
//     aaSorting: [],
//     ajax: "{{ route('admin.chapters.index') }}",
//     columns: [
//       { data: 'placeholder', name: 'placeholder' },
// { data: 'id', name: 'id' },
// { data: 'board_name', name: 'board.name' },
// { data: 'board.code', name: 'board.code' },
// { data: 'class_name', name: 'class.name' },
// { data: 'class.code', name: 'class.code' },
// { data: 'subject_name', name: 'subject.name' },
// { data: 'subject.code', name: 'subject.code' },
// { data: 'code', name: 'code' },
// { data: 'name', name: 'name' },
// { data: 'description', name: 'description' },
// { data: 'image', name: 'image', sortable: false, searchable: false },
// { data: 'status', name: 'status' },
// { data: 'is_active', name: 'is_active' },
// { data: 'modified_by_name', name: 'modified_by.name' },
// { data: 'actions', name: '{{ trans('global.actions') }}' }
//     ],
//     order: [[ 1, 'desc' ]],
//     pageLength: 100,
//   };
//   $('.datatable-Chapter').DataTable(dtOverrideGlobals);
//     $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
//         $($.fn.dataTable.tables(true)).DataTable()
//             .columns.adjust();
//     });
// });


var ajaxurl = "{{ route('admin.chapters.ajaxData') }}";
var addurl = '{{ route("admin.chapters.store") }}';
var editurl = '{{ route("admin.chapters.edit", ":id") }}';
var updateurl = '{{ route("admin.chapters.update", ":id") }}';
var deleteurl = '{{ route("admin.chapters.destroy", ":id") }}';
var dropImageurl = "{{ route('admin.chapters.storeMedia') }}";
    

   
</script>
<script src="{{ asset('js/setupjs.js') }}"></script>
<script>
    $("#board_id").change(function(){
        $.ajax({
            url: "{{ route('admin.subjects.get_by_classes') }}?board_id=" + $(this).val(),
            method: 'GET',
            success: function(data) {
                $('#class_id').html(data.html);
            }
        });
    });
    $("#class_id").change(function(){
        $.ajax({
            url: "{{ route('admin.chapters.get_by_subjects') }}?class_id=" + $(this).val(),
            method: 'GET',
            success: function(data) {
                $('#subject_id').html(data.html);
            }
        });
    });
</script>
@endsection

resources/views/admin/chapters/list.blade.php
@extends('layouts.adminpanel')
@section('content')

<main class="chapter-section">
        <div class="container-fluid">
            <div class="row">
                <!-- <div class="col-2">
                    <div class="filter">
                        <p><strong class="text-purple">Filters</strong></p>
                        <hr/>
                        <p><strong>Board</strong></p>
                        <div class="form-group mb-15">
                            <input type="search" class="form-control" placeholder="Search board" />
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">CBSE</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">ICSE</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">CVE</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">IB</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">State boards</label>
                        </div>
                        <a href="#" class="btn btn-link text-purple">15 More >></a>
                        <hr />
                        <p><strong>Standard / Class</strong></p>
                        <div class="form-group mb-15">
                            <input type="search" class="form-control" placeholder="Search board" />
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">1 std</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">2 std</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">3 std</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">4 std</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">5 std</label>
                        </div>
                        <a href="#" class="btn btn-link text-purple">45 More >></a>
                        <hr />
                        <p><strong>Subject</strong></p>
                        <div class="form-group mb-15">
                            <input type="search" class="form-control" placeholder="Search board" />
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Tamil</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">English</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Maths</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Sciense</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Computer Sciense</label>
                        </div>
                        <a href="#" class="btn btn-link text-purple">150 More >></a>

                    </div>
                </div> -->
                <div class="col-10">
                    <div class="row" id="tag_container">
                        <!-- <div class="col-4">
                            <div class="chapter-box">
                                <span class="text-orange text-small">10 Units</span>
                                <span class="text-small pull-right">Few hours ago</span>
                                <div class="media">
                                        <img class="align-self-start mr-3" src="{{ asset('img/profile.jpg') }}" alt="">
                                        <div class="media-body">
                                          <h5 class="mt-0">The importance local spices and herbs to the human health</h5>
                                        </div>
                                      </div>
                                      <div class="board-type chapter-btn"><span>CBSC Board</span> <span>10th std</span>
                                        <span>Science</span></div>
                                <p>Lorem ipsum dolor sit amet, Setur piscing elit, sed do mod tempor ididunt ut labore et dolore...</p>
                                <div class="row">
                                        <div class="col-4">CBSE Board
                                        </div>
                                        <div class="col-4 text-center">10 std
                                        </div>
                                        <div class="col-4 text-right">Science
                                        </div>
                                    </div>          
                 
                                   
                            </div>
                        </div> -->
                        <!-- <div class="row" id="tag_container"></div> -->
                        
                        

                    </div>
                </div>
            </div>
        </div>
    </main>

@endsection
@section('scripts')
@parent
<script>
    var ajaxurl = "{{ route('admin.chapters.ajaxData') }}";
    var addurl = '{{ route("admin.chapters.store") }}';
    var editurl = '{{ route("admin.chapters.edit", ":id") }}';
    var updateurl = '{{ route("admin.chapters.update", ":id") }}';
    var deleteurl = '{{ route("admin.chapters.destroy", ":id") }}';
    var dropImageurl = "{{ route('admin.chapters.storeMedia') }}";
    
    subview = "clist";
   
</script>
<script src="{{ asset('js/setupjs.js') }}"></script>

@endsection