routes/web.php
<?php


Auth::routes();
Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');

Route::redirect('/', '/login');
// Route::get('/home', function () {
//     if (session('status')) {
//         return redirect()->route('admin.home')->with('status', session('status'));
//     }

//     return redirect()->route('admin.home');
// });


// Route::get('/', 'Auth\LoginController@login')->name('login');
// Route::get('/admin/login', 'Admin\LoginController@login')->name('login');


Route::get('admin/login', 'Auth\LoginController@showAdminLoginForm')->name('auth.admin.login');
Route::get('register', 'Auth\RegisterController@showStudentRegisterForm')->name('auth.register.student');

Route::post('register', 'Auth\RegisterController@createStudent')->name('athu.register.student');
Route::get('get_by_classes', 'Admin\SubjectController@get_by_myclasses')->name('subjects.get_by_classes');

Route::get('/dashboard', function () {
    if (session('status')) {
        return redirect()->route('admin.dashboard')->with('status', session('status'));
    }

    return redirect()->route('admin.dashboard');
});

Route::group(['as' => 'user.','namespace' => 'User', 'middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('subjectsajaxData','HomeController@subjectAjaxData')->name('subjects.ajaxData');
    Route::get('/mycourse', 'HomeController@mycourse')->name('mycourse');
	Route::get('mycoursesubajaxData','HomeController@mycourseSubAjaxData')->name('mycourse.subAajaxData');
    Route::post('courseassignajaxData','HomeController@courseAssignAjaxData')->name('course.assignAjaxData');
    Route::get('chaptersajaxData','HomeController@chapterAjaxData')->name('chapters.ajaxData');
    Route::get('unitsajaxData','HomeController@unitAjaxData')->name('units.ajaxData');
    Route::get('qaajaxData','HomeController@QAAjaxData')->name('qa.ajaxData');
    Route::post('qaajaxData','HomeController@QAAjaxSubmitData')->name('qa.ajaxData');

    Route::get('/chapters/{id}', 'HomeController@chaptersIndex')->name('chapters'); 
    Route::get('/units/{id}', 'HomeController@unitsIndex')->name('units'); 
    Route::get('/qa/{id}', 'HomeController@QAIndex')->name('qa'); 

    Route::get('/profile', 'ProfileController@index')->name('profile'); 
    Route::post('/changepassword', 'ProfileController@changePassword')->name('changepassword');
});

//Clear all cache:
Route::get('clearall', function() {
    // $exitCode = Artisan::call('route:cache');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    return 'all cleared';
});




    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth','adminChecker']], function () {
    // Route::get('/', 'HomeController@index')->name('home'); 

    Route::get('/', 'DashboardController@index')->name('dashboard'); 



    Route::get('user-alerts/read', 'UserAlertsController@read');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('settings/permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('settings/roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('settings/users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // User Alerts
    Route::delete('user-alerts/destroy', 'UserAlertsController@massDestroy')->name('user-alerts.massDestroy');
    Route::resource('user-alerts', 'UserAlertsController', ['except' => ['edit', 'update']]);

    // Faq Categories
    Route::delete('faq-categories/destroy', 'FaqCategoryController@massDestroy')->name('faq-categories.massDestroy');
    Route::resource('faq-categories', 'FaqCategoryController');

    // Faq Questions
    Route::delete('faq-questions/destroy', 'FaqQuestionController@massDestroy')->name('faq-questions.massDestroy');
    Route::resource('faq-questions', 'FaqQuestionController');

    // Content Categories
    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
    Route::resource('content-categories', 'ContentCategoryController');

    // Content Tags
    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
    Route::resource('content-tags', 'ContentTagController');

    // Content Pages
    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
    Route::resource('content-pages', 'ContentPageController');

    // Boards
    Route::delete('boards/destroy', 'BoardController@massDestroy')->name('boards.massDestroy');
    Route::post('boards/media', 'BoardController@storeMedia')->name('boards.storeMedia');
    Route::resource('setup/boards', 'BoardController');
    Route::post('setup/boards/updates/{id}', 'BoardController@updates')->name('boards.updates');

    Route::get('ajaxData1','BoardController@ajaxData')->name('boards.ajaxData');
    Route::get('get_boards', 'BoardController@get_boards')->name('boards.get_boards');

    // My Classes
    Route::delete('my-classes/destroy', 'MyClassController@massDestroy')->name('my-classes.massDestroy');
    Route::post('my-classes/media', 'MyClassController@storeMedia')->name('my-classes.storeMedia');
    Route::resource('setup/my-classes', 'MyClassController');

    Route::get('ajaxData2','MyClassController@ajaxData')->name('my-classes.ajaxData');

    // Subjects
    Route::delete('subjects/destroy', 'SubjectController@massDestroy')->name('subjects.massDestroy');
    Route::post('subjects/media', 'SubjectController@storeMedia')->name('subjects.storeMedia');
    Route::resource('setup/subjects', 'SubjectController');
    
    Route::get('ajaxData3','SubjectController@ajaxData')->name('subjects.ajaxData');
    Route::get('get_by_classes', 'SubjectController@get_by_myclasses')->name('subjects.get_by_classes');

    // Chapters
    Route::delete('chapters/destroy', 'ChapterController@massDestroy')->name('chapters.massDestroy');
    Route::post('chapters/media', 'ChapterController@storeMedia')->name('chapters.storeMedia');
    Route::resource('setup/chapters', 'ChapterController');

    Route::get('ajaxData4','ChapterController@ajaxData')->name('chapters.ajaxData');
    Route::get('get_by_subjects', 'ChapterController@get_by_subjects')->name('chapters.get_by_subjects');
    Route::get('chapters/list', 'ChapterController@chapter_list')->name('chapters.list');

    // Units
    Route::delete('units/destroy', 'UnitController@massDestroy')->name('units.massDestroy');
    Route::post('units/media', 'UnitController@storeMedia')->name('units.storeMedia');
    Route::resource('units', 'UnitController');

    Route::get('ajaxData5','UnitController@ajaxData')->name('units.ajaxData');
    Route::get('get_by_chapters', 'UnitController@get_by_chapters')->name('units.get_by_chapters');
    Route::get('units/create', 'UnitController@create')->name('units.create');
    Route::post('units/sort_order', 'UnitController@sort_order')->name('units.sort_order');

    // Question Types
    Route::delete('question-types/destroy', 'QuestionTypeController@massDestroy')->name('question-types.massDestroy');
    Route::resource('question-types', 'QuestionTypeController');

    // Countries
    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountriesController');

    // States
    Route::delete('states/destroy', 'StateController@massDestroy')->name('states.massDestroy');
    Route::resource('states', 'StateController');

    // Cities
    Route::delete('cities/destroy', 'CityController@massDestroy')->name('cities.massDestroy');
    Route::resource('cities', 'CityController');

    // Students
    Route::delete('students/destroy', 'StudentController@massDestroy')->name('students.massDestroy');
    Route::resource('settings/students', 'StudentController');

    // Student Study Units
    Route::delete('student-study-units/destroy', 'StudentStudyUnitsController@massDestroy')->name('student-study-units.massDestroy');
    Route::resource('student-study-units', 'StudentStudyUnitsController');

    // Languages
    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
    Route::resource('languages', 'LanguageController');

    // Question Answers
    Route::delete('question-answers/destroy', 'QuestionAnswerController@massDestroy')->name('question-answers.massDestroy');
    Route::post('question-answers/media', 'QuestionAnswerController@storeMedia')->name('question-answers.storeMedia');
    Route::post('question-answers/parse-csv-import', 'QuestionAnswerController@parseCsvImport')->name('question-answers.parseCsvImport');
    Route::post('question-answers/process-csv-import', 'QuestionAnswerController@processCsvImport')->name('question-answers.processCsvImport');
    Route::resource('question-answers', 'QuestionAnswerController');

    Route::post('question-answers/sort_order', 'QuestionAnswerController@sort_order')->name('question-answers.sort_order');

    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyUserRequest;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Role;
use App\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class UsersController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('user_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        abort_if(Gate::denies('user_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $roles = Role::all()->pluck('title', 'id');

        return view('admin.users.create', compact('roles'));
    }

    public function store(StoreUserRequest $request)
    {
        $user = User::create($request->all());
        $user->roles()->sync($request->input('roles', []));

        return redirect()->route('admin.users.index');
    }

    public function edit(User $user)
    {
        abort_if(Gate::denies('user_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $roles = Role::all()->pluck('title', 'id');

        $user->load('roles');

        return view('admin.users.edit', compact('roles', 'user'));
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        $user->update($request->all());
        $user->roles()->sync($request->input('roles', []));

        return redirect()->route('admin.users.index');
    }

    public function show(User $user)
    {
        abort_if(Gate::denies('user_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $user->load('roles');

        return view('admin.users.show', compact('user'));
    }

    public function destroy(User $user)
    {
        abort_if(Gate::denies('user_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $user->delete();

        return back();
    }

    public function massDestroy(MassDestroyUserRequest $request)
    {
        User::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/User/ProfileController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use DB;
use Auth;
use App\Board;
use App\MyClass;
use App\Subject;
use App\Chapter;
use App\Unit;
use App\QuestionAnswer;
use App\StudentUnitAccessLog;
use App\StudentCourse;
use App\User;
use Gate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Symfony\Component\HttpFoundation\Response;

class ProfileController extends Controller
{
    public function index()
    {
    	$user = auth()->user();
    	$userId = $user['id'];
    	$data = User::leftJoin('students', function($join){
    		$join->on('students.studentid', '=', 'users.id')->where('students.deleted_at', '=', NULL);
    	})
    	->leftJoin('boards', 'students.board_id', '=', 'boards.id')
    	->leftJoin('my_classes', 'students.class_id', '=', 'my_classes.id')
    	->leftJoin('states', 'students.state_id', '=', 'states.id')
    	->leftJoin('countries', 'students.country_id', '=', 'countries.id')
    	->select('students.name AS studentName','students.email AS studentEmail','boards.name AS boardName','my_classes.name AS className')
    	->where('users.id','=',$userId)->get();
    	
    	return view('user.profile',compact('data'));
    }
    
    public function changePassword(Request $request)
    {
    	$user = new User();
    	$user->update(['password' =>Hash::make($request['password'])]);
    	
    	return true;
    }
}

resources/views/user/chapters.blade.php
@extends('layouts.user')
<div class="container">
    <div class="row">
    <section class="banner-section">
        <div class="container-fluid">
             <a href="{{ route('user.home') }}" class="text-warning"><i style="font-size: 20px;" class="fa fa-long-arrow-left" aria-hidden="true"></i></a><span class="text-warning"> back </span>
        </div>
	</section>
    </div>
</div>

<div class="title-card">
    <img class="bg-dark" src="{{ asset('img/default-img.jpg') }}" width="70" height="70">
    <div class="ml-2 p-2">
    	<h2>{!! $subject[0]->name !!}</h2>
      
    </div>
</div>

<div class="container">
    <div class="row">
    <section class="banner-sec">
        <div class="container-fluid">
             <a href="#" class="text-warn">Chapters</a>
             <!-- <a href="#" class="view-property">View all</a> -->
        </div>
    </section>
    </div>
</div>

<div class="row row m-2" id="tag_container"></div>

@section('scripts')
@parent
<script>
    var ajaxurl = "{{ route('user.chapters.ajaxData') }}";
    // console.log("subject id",{{$data['id']}});
// var addurl = '{{ route("admin.chapters.store") }}';
// var editurl = '{{ route("admin.chapters.edit", ":id") }}';
// var updateurl = '{{ route("admin.chapters.update", ":id") }}';
// var deleteurl = '{{ route("admin.chapters.destroy", ":id") }}';
// var dropImageurl = "{{ route('admin.chapters.storeMedia') }}";
    

   
</script>
<script src="{{ asset('js/user.js') }}"></script>
<script>
$(document).ready(function(){
    getById = "{{$data['id']}}";
    getData(page);

    });
</script>
@endsection

resources/views/user/home.blade.php
@extends('layouts.user')
            <!--Carousel Wrapper-->
            <div id="carousel" class="carousel slide carousel-fade" data-ride="carousel" style="margin-bottom: 1em !important">
                <!--Indicators-->
                <ol class="carousel-indicators">
                    <li data-target="#carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel" data-slide-to="1"></li>
                    <li data-target="#carousel" data-slide-to="2"></li>
                </ol>
                <!--/.Indicators-->
                <!--Slides-->
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <div class="view hm-white-slight">
                             <img  class="carousel-image" src="img/banner_carousel/carousel_1.png" alt="First slide">
                            <div class="mask"></div>
                        </div>
                        
                      <img src="{{ asset('img/logo.png') }}" alt="logo" class="carousel-logo">

                        <div class="carousel-cap">
                        <i>Welcome To <br>
                        Stress Free Studies</i>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <!--Mask color-->
                        <div class="view hm-white-slight">
                            <img class="carousel-image" src="img/banner_carousel/carousel_2.jpg" alt="Second slide">
                            <div class="mask"></div>
                        </div>
          
                       <img src="{{ asset('img/logo.png') }}" alt="logo" class="carousel-logo">
                       
                    </div>
                    <div class="carousel-item">
                        <!--Mask color-->
                        <div class="view hm-white-slight">
                            <img  class="carousel-image" src="img/banner_carousel/carousel_3.jpg" alt="Third slide">
                            <div class="mask"></div>
                        </div>
                      
                       
                     <img src="{{ asset('img/logo.png') }}" alt="logo" class="carousel-logo-3">
                    </div>
                </div>
                <!--/.Slides-->
                <!--Controls-->
                <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                <!--/.Controls-->
            </div>
            <!--/.Carousel Wrapper-->

<div class="container">
    <div class="row">
    <section class="banner-sec">
        <div class="container-fluid">
             <a href="{{ route('user.home') }}" class="text-warn">Courses for You</a>
             <a href="#" class="view-property">View all</a>
        </div>
	</section>
    </div>
</div>
<div class="row row m-2" id="tag_container"></div>

@section('scripts')
@parent
<script>
    var ajaxurl = "{{ route('user.subjects.ajaxData') }}";
// var addurl = '{{ route("admin.chapters.store") }}';
// var editurl = '{{ route("admin.chapters.edit", ":id") }}';
// var updateurl = '{{ route("admin.chapters.update", ":id") }}';
// var deleteurl = '{{ route("admin.chapters.destroy", ":id") }}';
// var dropImageurl = "{{ route('admin.chapters.storeMedia') }}";
    

   
</script>
<script src="{{ asset('js/user.js') }}"></script>
<script>getData(page)</script>
@endsection

resources/views/user/mycourse.blade.php
@extends('layouts.user')
<div class="container">
    <div class="row">
    <section class="banner-sec">
        <div class="container-fluid">
             <a href="{{ route('user.mycourse') }}" class="text-warn">My Courses</a>
        </div>
	</section>
    </div>
</div>
<div class="row row m-2" id="tag_container"></div>

@section('scripts')
@parent
<script>
    var ajaxurl = "{{ route('user.mycourse.subAajaxData') }}";
// var addurl = '{{ route("admin.chapters.store") }}';
// var editurl = '{{ route("admin.chapters.edit", ":id") }}';
// var updateurl = '{{ route("admin.chapters.update", ":id") }}';
// var deleteurl = '{{ route("admin.chapters.destroy", ":id") }}';
// var dropImageurl = "{{ route('admin.chapters.storeMedia') }}";
    

   
</script>
<script src="{{ asset('js/user.js') }}"></script>
<script>getData(page)</script>
@endsection

resources/views/user/profile.blade.php
@extends('layouts.user')
<link href="{{ asset('css/appcustom.css') }}" rel="stylesheet" />
<div class="container">
    <div class="row">
    <section class="banner-section">
        <div class="container-fluid d-inline-flex">
       	  <div class="text-left w-50">
             <a href="{{ route('user.home') }}" class="text-warning"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> back</a>
          </div>
          <div class="text-right w-50">
      		 <a href="#" class="text-warning" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
    		 {{ trans('global.logout') }}</a>&nbsp;<i class="nav-icon fas fa-fw fa-sign-out-alt"></i>
    	  </div> 
        </div>
	</section>
    </div>

    <div class="w-100 d-inline-flex">
    	<div class="w-50"><h1>Profile</h1></div>
    	<div class="pt-2 text-right w-50"><a data-target="#changePassword" data-toggle="modal" href="#">Change Password</a></div>
    </div>	
    <div class="p-2 d-inline-flex">
    	<img class="bg-dark" src="{{ asset('img/profile.png') }}" style="border-radius: 20px;" width="40" height="40">
    	<div class="ml-2 p-2"><p>{{$data[0]->studentName}}</p></div>
    </div>
    <div class="p-2 d-list">
	    <div class="form-group mb-2">
	    	<label>E-mail Id</label>
	    	<input type="text" class="form-control bg-white" id="name" name="name" value="{{$data[0]->studentEmail}}" readonly>
	    </div>
	    <div class="form-group mb-2">
	    	<label>My Board</label>
	    	<input type="text" class="form-control bg-white" id="name" name="name" value="{{$data[0]->boardName}}" readonly>
	    </div>
	    <div class="form-group mb-2">
	    	<label>My Class</label>
	    	<input type="text" class="form-control bg-white" id="name" name="name" value="{{$data[0]->className}}" readonly>
	    </div>
    </div>
</div>

<div class="modal fade" id="changePassword" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content pb-2">
                 <div class="modal-header">
                    <h5 class="modal-title"><span id="addFormModalLabel">Change Password</span></h5>
                    <button type="button" class="close text-danger" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                <form id="changePasswordForm" class="login100-form validate-form" method="POST" action="{{ route('user.changepassword') }}">
                
               
	                <div class="pt-2">  
	                <span class="error d-none text-danger">Passwords does not match.</span>
	                <span class="success d-none text-success">Your Password have Successfully updated.</span>	                  
                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
                        <input id="password" name="password" type="password" class="input100" required placeholder="{{ trans('global.login_password') }}" value="">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
                        <input id="password_confirmation" name="password_confirmation" type="password" class="input100" required placeholder="{{ trans('global.login_password_confirmation') }}" value="">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					</div>
					</form>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="submit btn btn-success">Change</button>
        			<button type="button" class="cancel btn btn-danger" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
    @section('scripts')
    <script>
    $("#changePassword .submit").on('click',function(){
    	var password = $('#password').val();
    	var passwordConf = $('#password_confirmation').val();
    	if((password == passwordConf)&&!(password=='')){
    		//$('#changePasswordForm').submit();
	        $.ajax({
	            url: "{{ route('user.changepassword') }}?password=" + password,
	            method: 'POST',
	            success: function(data) {
	                //$('#class_id').html(data.html);
	                //alert('done');
	                //$('#theModal').modal('hide');	                
	            	$('#changePassword .success').removeClass('d-none');
	            	setTimeout(function(){location.reload(); }, 1500);	            	
	            }
	        });
        }else{
			$('#changePassword .error').removeClass('d-none');
			//$('#changePassword').modal('show');				
        }
    });
    </script>
    @endsection

resources/views/user/qa.blade.php
<link href="{{ asset('css/flashcard.css') }}" rel="stylesheet" />
@extends('layouts.user')
@section('footer')
@stop

<div class="container">
    <div class="row">
    <section class="banner-section">
        <div class="container-fluid">
             <a href="{{ url('units/') }}/{{$units[0]->chapter_id}}" class="text-warning"><i style="font-size: 20px;" class="fa fa-long-arrow-left" aria-hidden="true"></i></a><span class="text-warning"> back </span>
        </div>
	</section>
    </div>
    <div class="row">
	    <div class="title-card">
		    <img class="bg-dark" src="{{ asset('img/default-img.jpg') }}" width="70" height="70">
		    <div class="ml-2 p-2">
		    	<h2>{!! $units[0]->name !!}</h2>
		    </div>
		</div>
	    <div class="col-md-12 text-center">
	        <button type="button" style="width: auto;font-size: 18px;" class="btn-primary btn-sm">
	        Mastered<br/>
	        <span id="master" class="">{!! $master !!}</span>
	        </button>
	        <button type="button" style="width: auto;font-size: 18px;" class="btn-primary btn-sm">
	        Familiar<br/>
	        <span id="familiar" class="">{!! $familiar !!}</span>
	        </button>
	        <button type="button" style="width: auto;font-size: 18px;" class="btn-primary btn-sm">
	        Not Familiar<br/>
	        <span id="notfamiliar" class="">{!! $notfamiliar !!}</span>
	        </button>
	     </div>
     </div>
</div>
<div class="sliderContainer" id="tag_container" style="margin-top:5%;"></div>

@section('scripts')
@parent
<script>
    var ajaxurl = "{{ route('user.qa.ajaxData') }}";
    // console.log("subject id",{{$data['id']}});
// var addurl = '{{ route("admin.chapters.store") }}';
// var editurl = '{{ route("admin.chapters.edit", ":id") }}';
// var updateurl = '{{ route("admin.chapters.update", ":id") }}';
// var deleteurl = '{{ route("admin.chapters.destroy", ":id") }}';
// var dropImageurl = "{{ route('admin.chapters.storeMedia') }}";

$(document).ready(function() {

    getById = "{{$data['id']}}";
    getData(page);

	
});

   
</script>
<script src="{{ asset('js/user.js') }}"></script>

@endsection

resources/views/user/units.blade.php
@extends('layouts.user')
<div class="container">
    <div class="row">
	    <section class="banner-section">
	        <div class="container-fluid">
	             <a href="{{ url('chapters/') }}/{{$chapters[0]->subject_id}}" class="text-warning"><i style="font-size: initial;font-size: 20px;" class="fa fa-long-arrow-left" aria-hidden="true"></i></a><span class="text-warning"> back </span>
	        </div>
		</section>
    </div>
</div>
<div class="title-card">
    <img class="bg-dark" src="{{ asset('img/default-img.jpg') }}" width="70" height="70">
    <div class="ml-2 p-2">
    	<h2>{!! $chapters[0]->name !!}</h2>
    </div>
</div>

<div class="container">
    <div class="row">
    <section class="banner-sec">
        <div class="container-fluid">
             <a href="#" class="text-warn">Units</a>
             <!-- <a href="#" class="view-property">View all</a> -->
        </div>
    </section>
    </div>
</div>
<div class="row row m-2" id="tag_container"></div>

@section('scripts')
@parent
<script>
    var ajaxurl = "{{ route('user.units.ajaxData') }}";
    // console.log("subject id",{{$data['id']}});
// var addurl = '{{ route("admin.chapters.store") }}';
// var editurl = '{{ route("admin.chapters.edit", ":id") }}';
// var updateurl = '{{ route("admin.chapters.update", ":id") }}';
// var deleteurl = '{{ route("admin.chapters.destroy", ":id") }}';
// var dropImageurl = "{{ route('admin.chapters.storeMedia') }}";
    

   
</script>
<script src="{{ asset('js/user.js') }}"></script>
<script>
$(document).ready(function(){
    getById = "{{$data['id']}}";
    getData(page);

    });
</script>
@endsection